version: '3.1'

services:
  #================================
  # APP
  #================================
  company-app:
    container_name: company-app
    build: .
    command: >
      bash -c "python /src/manage.py migrate
      && python /src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/company_app
    ports:
      - "8000:8000"
    networks:
      - company-network
    depends_on:
      - company-postgresql
      - company-redis
  #================================
  # POSTGRES
  #================================
  company-postgresql:
    container_name: company-postgresql
    image: postgres:14.1-alpine
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - ../.company_data/company-postgresql:/var/lib/postgresql/data/
    networks:
      - company-network

  #================================
  # REDIS
  #================================
  company-redis:
    container_name: company-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - company-network

#================================
# NETWORK
#================================
networks:
  company-network:
      name: company-network