# Generated by Django 5.1.1 on 2024-10-05 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(db_index=True, max_length=255, verbose_name='Фамилия')),
                ('first_name', models.CharField(db_index=True, max_length=255, verbose_name='Имя')),
                ('father_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees', verbose_name='Фото')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Оклад')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='departments.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'unique_together': {('first_name', 'last_name', 'father_name', 'age', 'position')},
            },
        ),
    ]
